version: '3.0'
networks:
    app-network:
        driver: bridge

services:
    db:
        image: mysql:latest
        container_name: mysql-db
        ports:
            - '3306:3306'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: yess
            MYSQL_USER: docker_pro
            MYSQL_PASSWORD: password
        networks:
            - app-network

    app:
        depends_on:
            - db
        container_name: nestjs-ddd
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        restart: always
        environment:
            DB_HOST: mysql-db
            DB_PORT: 3306
            DB_DATABASE: yess
            DB_USERNAME: docker_pro
            DB_PASSWORD: password
        networks:
            - app-network
