#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

FORBIDDEN_HTTPS_URL="https://github.com/PracticeEveryday/nestjs-ddd.git" # insert your remote url (https)
FORBIDDEN_SSH_URL="git@github.com:PracticeEveryday/nestjs-ddd.git" # insert your remote url (ssh)
FORBIDDEN_REF="refs/heads/main" # insert branch ref

remote="$1"
url="$2"

echo $remote
echo $url
echo $FORBIDDEN_HTTPS_URL
echo $FORBIDDEN_SSH_URL

if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
then
    echo "여기에 들어왔니혹시?"
    exit 0 # Forked Project 에서는 제한하지 않음
fi

if read local_ref local_sha remote_ref remote_sha
then
    if [ "$remote_ref" == "$FORBIDDEN_REF" ]
    then
        echo "DO NOT PUSH it main"
        exit 1 # 금지된 ref 로 push 를 실행하면 에러
    fi
fi

exit 0